"""intelligent reporting system

Revision ID: 5aaa8a518601
Revises: f3ddb7fee18f
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5aaa8a518601"
down_revision: str | None = "f3ddb7fee18f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_schedules",
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("report_type", sa.String(length=20), nullable=False),
        sa.Column("audience_role", sa.String(length=40), nullable=False),
        sa.Column("cron_expression", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_report_schedules_created_by_users")
        ),
        sa.PrimaryKeyConstraint("schedule_id", name=op.f("pk_report_schedules")),
    )
    op.create_table(
        "reports",
        sa.Column("report_id", sa.String(length=50), nullable=False),
        sa.Column("report_type", sa.String(length=20), nullable=False),
        sa.Column("audience_role", sa.String(length=40), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("data_snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("template_version", sa.String(length=40), nullable=False),
        sa.Column("analytics_version", sa.String(length=40), nullable=False),
        sa.Column("ml_model_versions", sa.JSON(), nullable=False),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pdf_location", sa.String(length=500), nullable=True),
        sa.Column("excel_location", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.String(length=4000), nullable=True),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("llm_provider", sa.String(length=30), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_reports_generated_by_users")
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_audience_role"), "reports", ["audience_role"], unique=False)
    op.create_index(op.f("ix_reports_report_type"), "reports", ["report_type"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_table(
        "procurement_tasks",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("contract_id", sa.Uuid(), nullable=True),
        sa.Column("financial_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("assigned_role", sa.String(length=40), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("ai_suggested", sa.Boolean(), nullable=False),
        sa.Column("approval_status", sa.String(length=20), nullable=False),
        sa.Column("evidence_bundle", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_procurement_tasks_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.contract_id"],
            name=op.f("fk_procurement_tasks_contract_id_contracts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_procurement_tasks_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.material_id"],
            name=op.f("fk_procurement_tasks_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_procurement_tasks_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_procurement_tasks")),
    )
    op.create_index(
        op.f("ix_procurement_tasks_action_type"), "procurement_tasks", ["action_type"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_tasks_priority"), "procurement_tasks", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_tasks_source_type"), "procurement_tasks", ["source_type"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_tasks_status"), "procurement_tasks", ["status"], unique=False
    )
    op.create_table(
        "report_evidence",
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.String(length=50), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("period", sa.String(length=60), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("previous_value", sa.JSON(), nullable=True),
        sa.Column("calculation_service", sa.String(length=120), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.report_id"], name=op.f("fk_report_evidence_report_id_reports")
        ),
        sa.PrimaryKeyConstraint("evidence_id", name=op.f("pk_report_evidence")),
    )
    op.create_index(op.f("ix_report_evidence_metric"), "report_evidence", ["metric"], unique=False)
    op.create_index(
        op.f("ix_report_evidence_report_id"), "report_evidence", ["report_id"], unique=False
    )
    op.create_table(
        "report_recommendations",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=300), nullable=False),
        sa.Column("reason", sa.String(length=800), nullable=False),
        sa.Column("expected_benefit", sa.String(length=500), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("suggested_owner", sa.String(length=100), nullable=False),
        sa.Column("suggested_due", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("disposition", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.report_id"],
            name=op.f("fk_report_recommendations_report_id_reports"),
        ),
        sa.PrimaryKeyConstraint("recommendation_id", name=op.f("pk_report_recommendations")),
    )
    op.create_index(
        op.f("ix_report_recommendations_report_id"),
        "report_recommendations",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "report_sections",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.String(length=50), nullable=False),
        sa.Column("section_key", sa.String(length=60), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.report_id"], name=op.f("fk_report_sections_report_id_reports")
        ),
        sa.PrimaryKeyConstraint("section_id", name=op.f("pk_report_sections")),
    )
    op.create_index(
        op.f("ix_report_sections_report_id"), "report_sections", ["report_id"], unique=False
    )
    op.create_table(
        "report_tasks",
        sa.Column("report_task_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.String(length=50), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.report_id"], name=op.f("fk_report_tasks_report_id_reports")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["procurement_tasks.task_id"],
            name=op.f("fk_report_tasks_task_id_procurement_tasks"),
        ),
        sa.PrimaryKeyConstraint("report_task_id", name=op.f("pk_report_tasks")),
    )
    op.create_index(op.f("ix_report_tasks_report_id"), "report_tasks", ["report_id"], unique=False)
    op.create_index(op.f("ix_report_tasks_task_id"), "report_tasks", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_tasks_task_id"), table_name="report_tasks")
    op.drop_index(op.f("ix_report_tasks_report_id"), table_name="report_tasks")
    op.drop_table("report_tasks")
    op.drop_index(op.f("ix_report_sections_report_id"), table_name="report_sections")
    op.drop_table("report_sections")
    op.drop_index(op.f("ix_report_recommendations_report_id"), table_name="report_recommendations")
    op.drop_table("report_recommendations")
    op.drop_index(op.f("ix_report_evidence_report_id"), table_name="report_evidence")
    op.drop_index(op.f("ix_report_evidence_metric"), table_name="report_evidence")
    op.drop_table("report_evidence")
    op.drop_index(op.f("ix_procurement_tasks_status"), table_name="procurement_tasks")
    op.drop_index(op.f("ix_procurement_tasks_source_type"), table_name="procurement_tasks")
    op.drop_index(op.f("ix_procurement_tasks_priority"), table_name="procurement_tasks")
    op.drop_index(op.f("ix_procurement_tasks_action_type"), table_name="procurement_tasks")
    op.drop_table("procurement_tasks")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_report_type"), table_name="reports")
    op.drop_index(op.f("ix_reports_audience_role"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("report_schedules")
    # ### end Alembic commands ###
