"""initial core schema

Revision ID: 5bb8e36e673c
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5bb8e36e673c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("category_code", sa.String(length=20), nullable=False),
        sa.Column("category_name", sa.String(length=120), nullable=False),
        sa.Column("parent_category_id", sa.Uuid(), nullable=True),
        sa.Column("criticality", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["categories.category_id"],
            name=op.f("fk_categories_parent_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("category_id", name=op.f("pk_categories")),
        sa.UniqueConstraint("category_code", name=op.f("uq_categories_category_code")),
    )
    op.create_table(
        "suppliers",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_code", sa.String(length=30), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=80), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("supplier_category", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("preferred_supplier", sa.Boolean(), nullable=False),
        sa.Column("strategic_supplier", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("baseline_lead_time_days", sa.Integer(), nullable=False),
        sa.Column("baseline_quality_rating", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("baseline_delivery_rating", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("risk_tier", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("supplier_id", name=op.f("pk_suppliers")),
    )
    op.create_index(op.f("ix_suppliers_active"), "suppliers", ["active"], unique=False)
    op.create_index(op.f("ix_suppliers_country"), "suppliers", ["country"], unique=False)
    op.create_index(op.f("ix_suppliers_risk_tier"), "suppliers", ["risk_tier"], unique=False)
    op.create_index(op.f("ix_suppliers_supplier_code"), "suppliers", ["supplier_code"], unique=True)
    op.create_index(
        op.f("ix_suppliers_supplier_name"), "suppliers", ["supplier_name"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN", "PROCUREMENT_ANALYST", "PROCUREMENT_MANAGER", "EXECUTIVE", name="role"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "materials",
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("material_code", sa.String(length=30), nullable=False),
        sa.Column("material_name", sa.String(length=160), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=10), nullable=False),
        sa.Column("standard_cost", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("criticality", sa.String(length=20), nullable=False),
        sa.Column("single_source_allowed", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
            name=op.f("fk_materials_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("material_id", name=op.f("pk_materials")),
    )
    op.create_index(op.f("ix_materials_category_id"), "materials", ["category_id"], unique=False)
    op.create_index(op.f("ix_materials_material_code"), "materials", ["material_code"], unique=True)
    op.create_table(
        "purchase_orders",
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("po_number", sa.String(length=30), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("required_delivery_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("buyer", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_purchase_orders_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("po_id", name=op.f("pk_purchase_orders")),
    )
    op.create_index(
        "ix_po_supplier_order_date", "purchase_orders", ["supplier_id", "order_date"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_order_date"), "purchase_orders", ["order_date"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_po_number"), "purchase_orders", ["po_number"], unique=True
    )
    op.create_index(op.f("ix_purchase_orders_status"), "purchase_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_table(
        "purchase_order_items",
        sa.Column("po_item_id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("line_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("expected_unit_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("price_variance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.material_id"],
            name=op.f("fk_purchase_order_items_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.po_id"],
            name=op.f("fk_purchase_order_items_po_id_purchase_orders"),
        ),
        sa.PrimaryKeyConstraint("po_item_id", name=op.f("pk_purchase_order_items")),
    )
    op.create_index(
        op.f("ix_purchase_order_items_material_id"),
        "purchase_order_items",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_items_po_id"), "purchase_order_items", ["po_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_order_items_po_id"), table_name="purchase_order_items")
    op.drop_index(op.f("ix_purchase_order_items_material_id"), table_name="purchase_order_items")
    op.drop_table("purchase_order_items")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_status"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_po_number"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_order_date"), table_name="purchase_orders")
    op.drop_index("ix_po_supplier_order_date", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_materials_material_code"), table_name="materials")
    op.drop_index(op.f("ix_materials_category_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_supplier_name"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_supplier_code"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_risk_tier"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_country"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_active"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_table("categories")
    # ### end Alembic commands ###
