"""complete local demo domain

Revision ID: 5ca08a2e7998
Revises: 5bb8e36e673c
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5ca08a2e7998"
down_revision: str | None = "5bb8e36e673c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=80), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("records_received", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("initiated_by", sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_pipeline_runs")),
    )
    op.create_index(op.f("ix_pipeline_runs_status"), "pipeline_runs", ["status"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users")),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        op.f("ix_audit_log_correlation_id"), "audit_log", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_entity_type"), "audit_log", ["entity_type"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("contract_number", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("contract_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("incoterm", sa.String(length=10), nullable=False),
        sa.Column("sla_otd_target", sa.Float(), nullable=False),
        sa.Column("sla_quality_target", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
            name=op.f("fk_contracts_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_contracts_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("contract_id", name=op.f("pk_contracts")),
        sa.UniqueConstraint("contract_number", name=op.f("uq_contracts_contract_number")),
    )
    op.create_index(op.f("ix_contracts_end_date"), "contracts", ["end_date"], unique=False)
    op.create_index(op.f("ix_contracts_status"), "contracts", ["status"], unique=False)
    op.create_index(op.f("ix_contracts_supplier_id"), "contracts", ["supplier_id"], unique=False)
    op.create_table(
        "pipeline_steps",
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_name", sa.String(length=40), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.run_id"],
            name=op.f("fk_pipeline_steps_run_id_pipeline_runs"),
        ),
        sa.PrimaryKeyConstraint("step_id", name=op.f("pk_pipeline_steps")),
    )
    op.create_index(op.f("ix_pipeline_steps_run_id"), "pipeline_steps", ["run_id"], unique=False)
    op.create_table(
        "supplier_risk_factors",
        sa.Column("risk_factor_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("risk_date", sa.Date(), nullable=False),
        sa.Column("financial_risk", sa.Float(), nullable=False),
        sa.Column("delivery_risk", sa.Float(), nullable=False),
        sa.Column("quality_risk", sa.Float(), nullable=False),
        sa.Column("geographic_risk", sa.Float(), nullable=False),
        sa.Column("dependency_risk", sa.Float(), nullable=False),
        sa.Column("price_risk", sa.Float(), nullable=False),
        sa.Column("overall_risk", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_supplier_risk_factors_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("risk_factor_id", name=op.f("pk_supplier_risk_factors")),
    )
    op.create_index(
        op.f("ix_supplier_risk_factors_overall_risk"),
        "supplier_risk_factors",
        ["overall_risk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_risk_factors_risk_date"),
        "supplier_risk_factors",
        ["risk_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_risk_factors_supplier_id"),
        "supplier_risk_factors",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("alert_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("financial_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_alerts_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.material_id"], name=op.f("fk_alerts_material_id_materials")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.supplier_id"], name=op.f("fk_alerts_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("alert_id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=40), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("invoice_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_due_date", sa.Date(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("invoice_status", sa.String(length=20), nullable=False),
        sa.Column("po_match_status", sa.String(length=20), nullable=False),
        sa.Column("duplicate_flag", sa.Boolean(), nullable=False),
        sa.Column("variance_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_id"], ["purchase_orders.po_id"], name=op.f("fk_invoices_po_id_purchase_orders")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_invoices_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("invoice_id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_invoices_invoice_number")),
    )
    op.create_index(
        op.f("ix_invoices_duplicate_flag"), "invoices", ["duplicate_flag"], unique=False
    )
    op.create_index(op.f("ix_invoices_invoice_date"), "invoices", ["invoice_date"], unique=False)
    op.create_index(op.f("ix_invoices_po_id"), "invoices", ["po_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_po_match_status"), "invoices", ["po_match_status"], unique=False
    )
    op.create_index(op.f("ix_invoices_supplier_id"), "invoices", ["supplier_id"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("po_item_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("planned_delivery_date", sa.Date(), nullable=False),
        sa.Column("actual_delivery_date", sa.Date(), nullable=False),
        sa.Column("quantity_expected", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("quantity_received", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("days_late", sa.Integer(), nullable=False),
        sa.Column("delivery_status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.po_item_id"],
            name=op.f("fk_deliveries_po_item_id_purchase_order_items"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_deliveries_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("delivery_id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("po_item_id", name=op.f("uq_deliveries_po_item_id")),
    )
    op.create_index(
        op.f("ix_deliveries_actual_delivery_date"),
        "deliveries",
        ["actual_delivery_date"],
        unique=False,
    )
    op.create_index(op.f("ix_deliveries_days_late"), "deliveries", ["days_late"], unique=False)
    op.create_index(op.f("ix_deliveries_supplier_id"), "deliveries", ["supplier_id"], unique=False)
    op.create_table(
        "quality_incidents",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("po_item_id", sa.Uuid(), nullable=False),
        sa.Column("incident_date", sa.Date(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("defect_type", sa.String(length=80), nullable=False),
        sa.Column("quantity_affected", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("root_cause_category", sa.String(length=80), nullable=False),
        sa.Column("resolution_status", sa.String(length=20), nullable=False),
        sa.Column("days_to_close", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.material_id"],
            name=op.f("fk_quality_incidents_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.po_item_id"],
            name=op.f("fk_quality_incidents_po_item_id_purchase_order_items"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_quality_incidents_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_quality_incidents")),
    )
    op.create_index(
        op.f("ix_quality_incidents_incident_date"),
        "quality_incidents",
        ["incident_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_incidents_severity"), "quality_incidents", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_quality_incidents_supplier_id"), "quality_incidents", ["supplier_id"], unique=False
    )
    op.add_column("purchase_orders", sa.Column("contract_id", sa.Uuid(), nullable=True))
    with op.batch_alter_table("purchase_orders") as batch_op:
        batch_op.create_foreign_key(
            op.f("fk_purchase_orders_contract_id_contracts"),
            "contracts",
            ["contract_id"],
            ["contract_id"],
        )
    op.add_column(
        "suppliers",
        sa.Column("base_price_competitiveness", sa.Float(), nullable=False, server_default="1"),
    )
    op.add_column(
        "suppliers", sa.Column("capacity", sa.Float(), nullable=False, server_default="1")
    )
    op.add_column(
        "suppliers",
        sa.Column("financial_stability", sa.Float(), nullable=False, server_default="80"),
    )
    op.add_column(
        "suppliers", sa.Column("country_risk", sa.Float(), nullable=False, server_default="20")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suppliers", "country_risk")
    op.drop_column("suppliers", "financial_stability")
    op.drop_column("suppliers", "capacity")
    op.drop_column("suppliers", "base_price_competitiveness")
    with op.batch_alter_table("purchase_orders") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_purchase_orders_contract_id_contracts"), type_="foreignkey"
        )
    op.drop_column("purchase_orders", "contract_id")
    op.drop_index(op.f("ix_quality_incidents_supplier_id"), table_name="quality_incidents")
    op.drop_index(op.f("ix_quality_incidents_severity"), table_name="quality_incidents")
    op.drop_index(op.f("ix_quality_incidents_incident_date"), table_name="quality_incidents")
    op.drop_table("quality_incidents")
    op.drop_index(op.f("ix_deliveries_supplier_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_days_late"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_actual_delivery_date"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_invoices_supplier_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_po_match_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_po_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_date"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_duplicate_flag"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_supplier_risk_factors_supplier_id"), table_name="supplier_risk_factors")
    op.drop_index(op.f("ix_supplier_risk_factors_risk_date"), table_name="supplier_risk_factors")
    op.drop_index(op.f("ix_supplier_risk_factors_overall_risk"), table_name="supplier_risk_factors")
    op.drop_table("supplier_risk_factors")
    op.drop_index(op.f("ix_pipeline_steps_run_id"), table_name="pipeline_steps")
    op.drop_table("pipeline_steps")
    op.drop_index(op.f("ix_contracts_supplier_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_end_date"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_audit_log_entity_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_correlation_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_pipeline_runs_status"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
