"""agent audit and action workflow

Revision ID: f3ddb7fee18f
Revises: 5ca08a2e7998
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f3ddb7fee18f"
down_revision: str | None = "5ca08a2e7998"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_interactions",
        sa.Column("agent_request_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("agent_name", sa.String(length=80), nullable=False),
        sa.Column("question", sa.String(length=1000), nullable=False),
        sa.Column("tools_called", sa.JSON(), nullable=False),
        sa.Column("entity_ids", sa.JSON(), nullable=False),
        sa.Column("model_provider", sa.String(length=30), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_latency_ms", sa.Integer(), nullable=False),
        sa.Column("tool_latency_ms", sa.Integer(), nullable=False),
        sa.Column("llm_latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_interactions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("agent_request_id", name=op.f("pk_agent_interactions")),
    )
    op.create_index(
        op.f("ix_agent_interactions_agent_name"), "agent_interactions", ["agent_name"], unique=False
    )
    op.create_index(
        op.f("ix_agent_interactions_session_id"), "agent_interactions", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_interactions_status"), "agent_interactions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agent_interactions_user_id"), "agent_interactions", ["user_id"], unique=False
    )
    op.create_table(
        "procurement_actions",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("financial_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("suggested_owner", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name=op.f("fk_procurement_actions_assigned_to_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.material_id"],
            name=op.f("fk_procurement_actions_material_id_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_procurement_actions_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("pk_procurement_actions")),
    )
    op.create_index(
        op.f("ix_procurement_actions_action_type"),
        "procurement_actions",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_actions_material_id"),
        "procurement_actions",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_actions_priority"), "procurement_actions", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_actions_status"), "procurement_actions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_actions_supplier_id"),
        "procurement_actions",
        ["supplier_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_procurement_actions_supplier_id"), table_name="procurement_actions")
    op.drop_index(op.f("ix_procurement_actions_status"), table_name="procurement_actions")
    op.drop_index(op.f("ix_procurement_actions_priority"), table_name="procurement_actions")
    op.drop_index(op.f("ix_procurement_actions_material_id"), table_name="procurement_actions")
    op.drop_index(op.f("ix_procurement_actions_action_type"), table_name="procurement_actions")
    op.drop_table("procurement_actions")
    op.drop_index(op.f("ix_agent_interactions_user_id"), table_name="agent_interactions")
    op.drop_index(op.f("ix_agent_interactions_status"), table_name="agent_interactions")
    op.drop_index(op.f("ix_agent_interactions_session_id"), table_name="agent_interactions")
    op.drop_index(op.f("ix_agent_interactions_agent_name"), table_name="agent_interactions")
    op.drop_table("agent_interactions")
    # ### end Alembic commands ###
